---
- name: Get public ip
  ipify_facts:
- route53:
    state: present
    zone: "{{ item.zone }}"
    record: "{{ item.record }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    hosted_zone_id: "{{ item.hosted_zone_id }}"
    type: A
    ttl: 7200
    value:
      - "{{ ipify_public_ip }}"
    overwrite: true  
    wait: yes
  loop: "{{ domains }}"
